//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Ayiza_DBEntities : DbContext
    {
        public Ayiza_DBEntities()
            : base("name=Ayiza_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address_Type> Address_Type { get; set; }
        public virtual DbSet<AirPort> AirPorts { get; set; }
        public virtual DbSet<Application_ChangeLog> Application_ChangeLog { get; set; }
        public virtual DbSet<Application_Type> Application_Type { get; set; }
        public virtual DbSet<Application_Type_Languages> Application_Type_Languages { get; set; }
        public virtual DbSet<Appointment_Type> Appointment_Type { get; set; }
        public virtual DbSet<Asset_Type> Asset_Type { get; set; }
        public virtual DbSet<Business_Type> Business_Type { get; set; }
        public virtual DbSet<Chart_Of_Accounts> Chart_Of_Accounts { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Communication_Category> Communication_Category { get; set; }
        public virtual DbSet<Communication_Type> Communication_Type { get; set; }
        public virtual DbSet<Company_Code> Company_Code { get; set; }
        public virtual DbSet<Company_Type> Company_Type { get; set; }
        public virtual DbSet<Control_AC_Type> Control_AC_Type { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Currency_Category> Currency_Category { get; set; }
        public virtual DbSet<Currency_Category_AppType_Languages> Currency_Category_AppType_Languages { get; set; }
        public virtual DbSet<Currency_Category_ChangeLog> Currency_Category_ChangeLog { get; set; }
        public virtual DbSet<Currency_ChangeLog> Currency_ChangeLog { get; set; }
        public virtual DbSet<Currency_Languages> Currency_Languages { get; set; }
        public virtual DbSet<Date_Format> Date_Format { get; set; }
        public virtual DbSet<Decimal_Format> Decimal_Format { get; set; }
        public virtual DbSet<Email_Type> Email_Type { get; set; }
        public virtual DbSet<Expense_Category> Expense_Category { get; set; }
        public virtual DbSet<Expense_Type> Expense_Type { get; set; }
        public virtual DbSet<Financial_Year> Financial_Year { get; set; }
        public virtual DbSet<Form_Of_Address_Type> Form_Of_Address_Type { get; set; }
        public virtual DbSet<Frequency> Frequencies { get; set; }
        public virtual DbSet<FX_Rate_Source> FX_Rate_Source { get; set; }
        public virtual DbSet<FX_Rate_Type> FX_Rate_Type { get; set; }
        public virtual DbSet<FY_Periods> FY_Periods { get; set; }
        public virtual DbSet<Gender_Type> Gender_Type { get; set; }
        public virtual DbSet<GL_Account_Text> GL_Account_Text { get; set; }
        public virtual DbSet<GL_Account_Type> GL_Account_Type { get; set; }
        public virtual DbSet<Identification_Type> Identification_Type { get; set; }
        public virtual DbSet<Insurance_Type> Insurance_Type { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Lease_Type> Lease_Type { get; set; }
        public virtual DbSet<Legal_Persons> Legal_Persons { get; set; }
        public virtual DbSet<Marital_Status_Type> Marital_Status_Type { get; set; }
        public virtual DbSet<MESS_Type_ChangeLog> MESS_Type_ChangeLog { get; set; }
        public virtual DbSet<Message_Codes> Message_Codes { get; set; }
        public virtual DbSet<Message_Codes_ChangeLog> Message_Codes_ChangeLog { get; set; }
        public virtual DbSet<Message_Codes_Languages> Message_Codes_Languages { get; set; }
        public virtual DbSet<Message_Type> Message_Type { get; set; }
        public virtual DbSet<Message_Type_Languages> Message_Type_Languages { get; set; }
        public virtual DbSet<Mode_Of_Transport> Mode_Of_Transport { get; set; }
        public virtual DbSet<Month> Months { get; set; }
        public virtual DbSet<Nationality> Nationalities { get; set; }
        public virtual DbSet<Officer_Type> Officer_Type { get; set; }
        public virtual DbSet<Port_Type> Port_Type { get; set; }
        public virtual DbSet<Priority_Type> Priority_Type { get; set; }
        public virtual DbSet<Security_Type> Security_Type { get; set; }
        public virtual DbSet<Service_Usage> Service_Usage { get; set; }
        public virtual DbSet<Sex> Sexes { get; set; }
        public virtual DbSet<Share_Class> Share_Class { get; set; }
        public virtual DbSet<State_Region> State_Region { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Tax_Office> Tax_Office { get; set; }
        public virtual DbSet<Time_Zone> Time_Zone { get; set; }
        public virtual DbSet<Transaction_Type> Transaction_Type { get; set; }
        public virtual DbSet<Unit_Of_Measurement> Unit_Of_Measurement { get; set; }
        public virtual DbSet<User_Group> User_Group { get; set; }
        public virtual DbSet<User_Type> User_Type { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<VAT_Schema> VAT_Schema { get; set; }
        public virtual DbSet<Block_Chain> Block_Chain { get; set; }
        public virtual DbSet<Environment> Environments { get; set; }
    }
}
