//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Block_Chain
    {
        public int AY_F_BLCKCHAIN_ID { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_BLCKCHAIN_YEAR { get; set; }
        public string AY_F_BLCKCHAIN_FR { get; set; }
        public string AY_F_BLCKCHAIN_TO { get; set; }
        public string AY_F_BLCKCHAIN_GEN { get; set; }
        public string AY_F_BLCKCHAIN_CN { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    }
}
