//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public City()
        {
            this.AirPorts = new HashSet<AirPort>();
        }
    
        public int AY_F_City_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_CITY_CODE { get; set; }
        public string AY_F_LANG_CODE { get; set; }
        public string AY_F_CTRY_CODE { get; set; }
        public string AY_F_STATE_CODE { get; set; }
        public Nullable<int> AY_F_LANG_Id { get; set; }
        public Nullable<int> AY_F_Country_Id { get; set; }
        public Nullable<int> AY_F_State_Region_Id { get; set; }
        public string AY_F_CITY_TEXT { get; set; }
        public string AY_F_TIZO_CODE { get; set; }
        public string AY_F_City_Time_Zone { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirPort> AirPorts { get; set; }
        public virtual Country Country { get; set; }
        public virtual Language Language { get; set; }
        public virtual State_Region State_Region { get; set; }
    }
}
