//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company_Code
    {
        public int AY_F_Company_Code_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_COMP_CODE { get; set; }
        public string AY_F_LANG_CODE { get; set; }
        public Nullable<int> AY_F_LANG_Id { get; set; }
        public string AY_F_BUST_TYPE { get; set; }
        public Nullable<int> AY_Business_Type_Id { get; set; }
        public string AY_F_AYIZA_NETCODE { get; set; }
        public string AY_F_COA_CODE { get; set; }
        public Nullable<int> AY_Chart_Of_Accounts_ID { get; set; }
        public string AY_F_LCOA_CODE { get; set; }
        public Nullable<int> AY_Chart_Of_Accounts_ID_LCOA { get; set; }
        public string AY_F_BCURR_CODE { get; set; }
        public Nullable<int> AY_F_CURR_Id { get; set; }
        public string AY_F_BFXRATE_TYPE { get; set; }
        public Nullable<int> AY_FX_RATE_TYPE_ID { get; set; }
        public string AY_F_GCURR_CODE { get; set; }
        public Nullable<int> AY_F_CURR_Id_GCURR { get; set; }
        public string AY_F_GFXRATE_TYPE { get; set; }
        public Nullable<int> AY_FX_RATE_TYPE_ID_GFXRATE { get; set; }
        public string AY_F_FINYEAR_CODE { get; set; }
        public Nullable<int> AY_Financial_Year_Id { get; set; }
        public string AY_F_ACCREF_DATE { get; set; }
        public string AY_F_VAT_REG { get; set; }
        public string AY_F_VAT_COUNTRY { get; set; }
        public Nullable<int> AY_F_Country_Id { get; set; }
        public string AY_F_VAT_REGNO { get; set; }
        public string AY_F_VREG_DATE { get; set; }
        public string AY_F_VEFF_DATE { get; set; }
        public string AY_F_VAT_SCHEME { get; set; }
        public Nullable<int> AY_F_VAT_Schema_Id { get; set; }
        public string AY_F_VFRET_DATE { get; set; }
        public string AY_F_VAT_STATUS { get; set; }
        public Nullable<int> AY_F_Status_Id { get; set; }
        public string AY_F_VAT_STDATE { get; set; }
        public string AY_F_CORP_COUNTRY { get; set; }
        public Nullable<int> AY_F_Country_Id_CORP { get; set; }
        public string AY_F_TAX_REG { get; set; }
        public string AY_F_CORP_REGNO { get; set; }
        public string AY_F_CORP_REFNO { get; set; }
        public string AY_F_CORP_OFFICE { get; set; }
        public Nullable<int> AY_F_Tax_Office_Id { get; set; }
        public string AY_F_CORPLF_DATE { get; set; }
        public string AY_F_CORPNF_DATE { get; set; }
        public string AY_F_CORP_STATUS { get; set; }
        public Nullable<int> AY_F_Status_Id_CORP { get; set; }
        public string AY_F_CORP_STDATE { get; set; }
        public string AY_F_PAYROLL_REG { get; set; }
        public string AY_F_PAYE_COUNTRY { get; set; }
        public Nullable<int> AY_F_Country_Id_PAYE { get; set; }
        public string AY_F_PAYE_CODE { get; set; }
        public string AY_F_PAYE_ACCREF { get; set; }
        public string AY_F_PAYE_OFFICE { get; set; }
        public Nullable<int> AY_F_Tax_Office_Id_PAYE { get; set; }
        public string AY_F_PAYE_STATUS { get; set; }
        public Nullable<int> AY_F_Status_Id_PAYE { get; set; }
        public string AY_F_PAYE_STDATE { get; set; }
        public string AY_F_COMP_TYPE { get; set; }
        public Nullable<int> AY_COMPANY_TYPE_ID { get; set; }
        public string AY_F_CH_REGCTRY { get; set; }
        public Nullable<int> AY_F_Country_Id_REGCTRY { get; set; }
        public string AY_F_CH_REGNO { get; set; }
        public string AY_F_CH_REGDATE { get; set; }
        public string AY_F_CH_STATUS { get; set; }
        public Nullable<int> AY_F_Status_Id_CH { get; set; }
        public string AY_F_CHSTAT_DATE { get; set; }
        public string AY_F_CHLRMUT_DATE { get; set; }
        public string AY_F_CHNRMUTO_DATE { get; set; }
        public string AY_F_CHNRDUE_DATE { get; set; }
        public string AY_F_CHLAMUT_DATE { get; set; }
        public string AY_F_CHNAMUTO_DATE { get; set; }
        public string AY_F_CHNADUE_DATE { get; set; }
        public string AY_F_CHLML_DATE { get; set; }
        public string AY_F_TIMZ_CODE { get; set; }
        public Nullable<int> AY_Time_Zone_Id_CODE { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public string AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE_ { get; set; }
        public string AY_F_LAST_CNG_TIME_ { get; set; }
        public string AY_F_LAST_CHG_BY__ { get; set; }
    
        public virtual Business_Type Business_Type { get; set; }
        public virtual Chart_Of_Accounts Chart_Of_Accounts { get; set; }
        public virtual Chart_Of_Accounts Chart_Of_Accounts1 { get; set; }
        public virtual Company_Type Company_Type { get; set; }
        public virtual Status Status { get; set; }
        public virtual Country Country { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual Language Language { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Country Country1 { get; set; }
        public virtual VAT_Schema VAT_Schema { get; set; }
        public virtual Status Status2 { get; set; }
        public virtual Country Country2 { get; set; }
        public virtual Tax_Office Tax_Office { get; set; }
        public virtual Status Status3 { get; set; }
        public virtual Country Country3 { get; set; }
        public virtual Tax_Office Tax_Office1 { get; set; }
        public virtual Financial_Year Financial_Year { get; set; }
        public virtual FX_Rate_Type FX_Rate_Type { get; set; }
        public virtual FX_Rate_Type FX_Rate_Type1 { get; set; }
        public virtual Time_Zone Time_Zone { get; set; }
    }
}
