//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Country
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Country()
        {
            this.AirPorts = new HashSet<AirPort>();
            this.Cities = new HashSet<City>();
            this.Company_Code = new HashSet<Company_Code>();
            this.Company_Code1 = new HashSet<Company_Code>();
            this.Company_Code2 = new HashSet<Company_Code>();
            this.Company_Code3 = new HashSet<Company_Code>();
            this.Port_Type = new HashSet<Port_Type>();
            this.State_Region = new HashSet<State_Region>();
            this.Tax_Office = new HashSet<Tax_Office>();
            this.VAT_Schema = new HashSet<VAT_Schema>();
        }
    
        public int AY_F_Country_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_CTRY_CODE { get; set; }
        public string AY_F_CURR_CODE { get; set; }
        public string AY_F_LANG_CODE { get; set; }
        public string AY_F_TIMZ_CODE { get; set; }
        public Nullable<int> AY_F_CURR_Id { get; set; }
        public Nullable<int> AY_F_LANG_ID { get; set; }
        public Nullable<int> AY_Time_Zone_Id { get; set; }
        public string AY_F_CTRY_TEXT { get; set; }
        public string AY_F_CTRY_ISO { get; set; }
        public string AY_F_IDD_CODE { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirPort> AirPorts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<City> Cities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Code> Company_Code { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Code> Company_Code1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Code> Company_Code2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Company_Code> Company_Code3 { get; set; }
        public virtual Currency Currency { get; set; }
        public virtual Language Language { get; set; }
        public virtual Time_Zone Time_Zone { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Port_Type> Port_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<State_Region> State_Region { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax_Office> Tax_Office { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VAT_Schema> VAT_Schema { get; set; }
    }
}
