//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expense_Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expense_Category()
        {
            this.Expense_Category1 = new HashSet<Expense_Category>();
        }
    
        public int AY_F_Expense_Category_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_EXP_TYPE { get; set; }
        public string AY_F_LANG_CODE { get; set; }
        public string AY_F_EXP_CAT { get; set; }
        public Nullable<int> AY_F_LANG_ID { get; set; }
        public Nullable<int> AY_F_Communication_Type_Id_Self { get; set; }
        public string AY_F_EXPTYTEXT { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Expense_Category> Expense_Category1 { get; set; }
        public virtual Expense_Category Expense_Category2 { get; set; }
        public virtual Language Language { get; set; }
    }
}
