//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MESS_Type_ChangeLog
    {
        public int AY_F_MESS_Type_CL_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_Field_ID { get; set; }
        public string AY_OLD_VALUE { get; set; }
        public string AY_NEW_VALUE { get; set; }
        public string AY_ACTION { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    }
}
