//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message_Type
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Message_Type()
        {
            this.Message_Codes = new HashSet<Message_Codes>();
            this.Message_Type_Languages = new HashSet<Message_Type_Languages>();
        }
    
        public int AY_F_Message_Type_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_MESSG_TYPE { get; set; }
        public string AY_F_MESSG_TEXT { get; set; }
        public Nullable<int> AY_F_APPL_TYPE_Id { get; set; }
        public string AY_F_APPL_TYPE { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    
        public virtual Application_Type Application_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_Codes> Message_Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Message_Type_Languages> Message_Type_Languages { get; set; }
    }
}
