//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction_Type
    {
        public int AY_F_Transaction_Type_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_TRANS_TYPE { get; set; }
        public string AY_F_LANG_CODE { get; set; }
        public string AY_F_APPL_TYPE { get; set; }
        public string AY_F_FXRATE_TYPE { get; set; }
        public Nullable<int> AY_F_LANG_Id { get; set; }
        public Nullable<int> AY_F_APPL_Id { get; set; }
        public Nullable<int> AY_FX_RATE_TYPE_ID { get; set; }
        public string AY_F_TRANSTY_TEXT { get; set; }
        public string AY_F_NUMRNG_ID { get; set; }
        public string AY_F_BLOCKCHAIN_ID { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
    
        public virtual Application_Type Application_Type { get; set; }
        public virtual FX_Rate_Type FX_Rate_Type { get; set; }
        public virtual Language Language { get; set; }
    }
}
