//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int AY_F_Users_Id { get; set; }
        public Nullable<int> AY_ENV_ID { get; set; }
        public string AY_F_FR_DATE { get; set; }
        public string AY_F_TO_DATE { get; set; }
        public string AY_F_USER_ID { get; set; }
        public Nullable<int> AY_F_USER_LOCKED { get; set; }
        public string AY_T_FOA_TYPE { get; set; }
        public Nullable<int> AY_Form_Of_Address_Type_Id { get; set; }
        public string AY_F_USER_FN { get; set; }
        public string AY_F_USER_LN { get; set; }
        public string AY_F_USER_PW { get; set; }
        public string AY_F_CTRY_CODE { get; set; }
        public string AY_F_CREATE_DATE { get; set; }
        public string AY_F_CREATE_TIME { get; set; }
        public Nullable<int> AY_F_CREATED_BY { get; set; }
        public string AY_F_LAST_CHG_DATE { get; set; }
        public string AY_F_LAST_CNG_TIME { get; set; }
        public Nullable<int> AY_F_LAST_CHG_BY { get; set; }
        public string AY_F_LANG_CODE { get; set; }
        public Nullable<int> AY_F_LANG_Id { get; set; }
        public string AY_F_UT_CODE { get; set; }
        public Nullable<int> AY_User_Type_Id { get; set; }
        public string AY_F_UG_CODE { get; set; }
        public Nullable<int> AY_User_Group_Id { get; set; }
        public string AY_F_DF_CODE { get; set; }
        public Nullable<int> AY_F_DF_Id { get; set; }
        public string AY_F_DEC_CODE { get; set; }
        public Nullable<int> AY_F_DEC_Id { get; set; }
        public string AY_F_STATUS_CODE { get; set; }
        public Nullable<int> AY_F_Status_Id { get; set; }
        public string AY_F_TIMZ_CODE { get; set; }
        public Nullable<int> AY_Time_Zone_Id { get; set; }
    
        public virtual Date_Format Date_Format { get; set; }
        public virtual Decimal_Format Decimal_Format { get; set; }
        public virtual Form_Of_Address_Type Form_Of_Address_Type { get; set; }
        public virtual Language Language { get; set; }
        public virtual Status Status { get; set; }
        public virtual Time_Zone Time_Zone { get; set; }
        public virtual User_Group User_Group { get; set; }
        public virtual User_Type User_Type { get; set; }
    }
}
